@startuml
actor 定时任务
participant 渠道系统
participant FTP主机
database 数据库

定时任务->FTP主机:下载A文件
FTP主机->定时任务:返回A文件
定时任务->定时任务:解析A文件
定时任务->渠道系统:同步A数据
渠道系统->数据库:保存A同步数据
数据库->渠道系统:返回A同步数据结果
渠道系统->定时任务:返回A同步数据结果
@enduml